### ISSUE TITLE
list of tutorials to add [do not close]

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio-tutorials#16]
- solvers_nonlinear
  - [ ] newton-raphson 
  - [ ] newton-raphson custom types
  - [ ] gauss-newton
  - [ ] gauss-newton custom types
  - [ ] gauss-newtonQR
  - [ ] gauss-newtonQR custom types
  - [ ] lm
  - [ ] lm custom types

- ode_advancers
  - [ ] `advance_n_times`
  - [ ] `advance_n_times_and_observe` 
  - [ ] `advance_n_times` with custom dt setter
  - [ ] `advance_n_times_and_observe` with custom dt setter and 

- ode_steppers
  - [x] explicit 
  - [x] explicit custom types 
  - [ ] implicit 
  - [ ] implicit custom types 

- rom 
  - linear decoder
  - custom decoder 
  - galerkin 
  - etc

**Comment by MikolajZuzek** [comment]
### Notes
* links: [published www](https://pressio.github.io/pressio-tutorials/html/md_pages_solvers_nonlinear_tutorial_1.html) | [doc files](https://github.com/Pressio/pressio-tutorials/tree/main/docs/pages) | [C++ source](https://github.com/Pressio/pressio-tutorials/tree/main/tutorials)
* start with non-linear solvers: Gauss-Newton with QR, Levenberg-Marquardt and IRLS
* look up the relevant code and sample problems in [Pressio tests](https://github.com/Pressio/pressio/tree/main/tests);
* fill in the documentation with clean tutorial code first, then we'll expand on comments and explanation sections;
* build the docs with `pressio-builder` (see [HowTo](https://github.com/Pressio/pressio/issues/309#issuecomment-922666293)).

> Note: watch for errors in MD files - if the preprocessor that pastes source code (`@codesnippet` + path.cc + line range) busts your docs file, you can recover from `*.backup`

**Comment by fnrizzi** [comment]
need to fully revise this
