### ISSUE TITLE
tutorial3 compilation error

### ISSUE THREAD

**Issue by burgreen** [Pressio/pressio-tutorials#4]
Tutorials 1 and 2 compile and run fine. Tutorial 3 gives the following error:

install/include/ode/src/explicit/./impl/ode_explicit_euler_stepper_impl.hpp:178:5: error: no matching function for call to 'update'
    ::pressio::ops::update(stateInOut, one, auxRhs0, dt);

FYI, I am using a custom builder, not cmake.

**Comment by fnrizzi** [comment]
@burgreen 
Hi! Thanks for trying our code and bringing this up. 
Indeed, I have not updated the tutorials based on the new release 0.5.1 (of a few days ago). I will fix the tutorials right away and notify you ok? I will make a new tag to be in sync with the main repos.

**Comment by fnrizzi** [comment]
@burgreen just fixed and pushed the release to sync with main c++ repo. 
Also, sorry for not having a decent set of tutorials yet...  I know it lacks quite a bit of stuff. Just trying to keep up with priorities. In a couple months, however, tutorials and documentation will become top priority, so stay tuned please :) 

In meantime, here is something to look at: 
- the regression tests for Burgers1d: https://github.com/Pressio/pressio/tree/master/tests/rom/burgers1d
will likely become material for tutorials.
- also, we have made some progress on the documentation for pressio: https://pressio.github.io/
- the Python bindings, see: https://pressio.github.io/pressio4py/html/index.html 
The Python website is the most updated one and you can already see a few practical demos for doing ROMs that I just pushed today

**Comment by burgreen** [comment]
@fnrizzi Many thanks for your quick responses and fix. Tutorial 3 works now. 

Thank you for the additional tutorial tips! I will move on to the Burgers regression tests now.

**Comment by fnrizzi** [comment]
just in case, if you look at the Burgers tests, the implementations (with various data structures) are here: https://github.com/Pressio/pressio/tree/master/packages/apps/src/burgers1d
